name: code_gnn
channels:
  - pytorch
  - pyg
  - torch
  - conda-forge
  - defaults
  - dglteam
dependencies:
  - cudatoolkit=10.2.89
  - dgl-cuda10.2=0.7.1
  - gensim=4.1.2
  - jupyter=1.0.0
  - networkx=2.6.3
  - numpy=1.21.2
  - pandas=1.3.3
  - pip=21.2.4
  - pyg=2.0.1
  - pytorch=1.9.1
  - scikit-learn=1.0
  - scipy=1.7.1
  - tensorboard=2.6.0
  - torchaudio=0.9.1
  - torchvision=0.2.2
  - tqdm=4.62.3
  - transformers=4.11.2
  - pip:
    - cpgqls-client==0.0.9
